### ISSUE TITLE
Only Sticky Column

### ISSUE THREAD

**Issue by rajputvai** [terrymun/StickySort#2]
Hi Terrymun,

Can you please tell me how can I stick only column?

**Comment by terrymun** [comment]
Yes, this should be possible by a slight modification to the script. I promise to look at this and integrate this as part of the plugin options when I have time.

**Comment by xcelpixel** [comment]
Great work! What if we want to add it for Jquery Datatable. It works perfectly but offset of sticky header won’t work accurately.

Thanks

**Comment by xcelpixel** [comment]
buzz
