### ISSUE TITLE
Provide support for $(window).on('load', function(){...

### ISSUE THREAD

**Issue by CallMeTuesday** [terrymun/StickySort#3]
Might be nice to provide support for using the .on method vs. the .load as it's been deprecated. Just a thought.

**Comment by terrymun** [comment]
I would like to see where it is stated in the jQuery API that `.load()` is deprecated. It is simply a shorthand for `.on('load')`.

**Comment by CallMeTuesday** [comment]
http://cl.ly/image/2k2o2h441U0v

#### .load as event

https://api.jquery.com/load-event/
Description: Bind an event handler to the "load" JavaScript event.

#### .load as ajax

https://api.jquery.com/load/
Description: Load data from the server and place the returned HTML into the matched element.
