### ISSUE TITLE
Activate sticky when scrolling on a table container vs. $window

### ISSUE THREAD

**Issue by CallMeTuesday** [terrymun/StickySort#4]
Awesome work, thank you!

I'd like to use this tool however I'd prefer to scroll on a table with a set height v.s scrolling on window. How would I go about doing that?

```
div{style=height: 500px; overflow:scroll}
    table
        thead....
```

**Comment by terrymun** [comment]
That is possible—check the markup for the final example with biaxial header overflows: http://terrymun.github.io/StickySort/#final

Simply force a height on the `.sticky-wrap` class, which wraps your table(s).
