### ISSUE TITLE
Sticky Header with jQuery Datatable plugin

### ISSUE THREAD

**Issue by xcelpixel** [terrymun/StickySort#5]
Great work! What if we want to add it for Jquery Datatable. It works perfectly but offset of sticky header won’t work accurately.

Thanks

**Comment by terrymun** [comment]
Do you have an example to show what is not working?

**Comment by xcelpixel** [comment]
![datatable](https://cloud.githubusercontent.com/assets/8590435/8511191/07169e50-2326-11e5-9c06-b44549870bba.png)

As you can see in the screenshot.Header is clipping from the middle.In fact, it works fine but when you turn on DataTable's Pagination and List Numbering then it won't detect the header offset.

Thanks

**Comment by terrymun** [comment]
You will have to override how the top position is calculated then. The very primitive nature of this plugin means that you will have to manually override how the vertical offset of the sticky header is computed. This might change in the future if I have time to rewrite the code base into a more standards-friendly plugin implementation, which will allow more customisation.
